### ISSUE TITLE
No examples for population statistics requests

### ISSUE THREAD

**Issue by brianmcdonald** [UGA-ITOSHumanitarianGIS/CODV2API#11]
Hi folks. I'm trying to figure out the syntax for calling population statistics, I can't see any examples in the documentation.
For instance `https://beta.itos.uga.edu/CODV2API/api/v1/themes/cod-ab/locations/SDN/versions/current/geoJSON/2` gives me admin boundaries for Sudan but  replacing "cod-ab" with "cod-ps" doesn't provide population start (even when using a different format.

Thanks for developing the API but please provide better documentation.

**Comment by UGA-ITOSHumanitarianGIS** [comment]
Thanks for your feedback! We will provide updates. The plan is to allow for the output. A sample is available for Liberia in vector tile format here: https://itos-humanitarian.s3.amazonaws.com/v1/VectorTile/COD_LBR/Admin/{z}/{x}/{y}.pbf see a preview here:https://jsfiddle.net/dsct1y0L/

**Comment by UGA-ITOSHumanitarianGIS** [comment]
Adding Afghanistan 2021 population statistics

**Comment by UGA-ITOSHumanitarianGIS** [comment]
https://apps.itos.uga.edu/CODV2API/api/v1/themes/cod-ps/lookup/Get/1/af
https://apps.itos.uga.edu/CODV2API/api/v1/themes/cod-ps/lookup/Get/0/af
https://apps.itos.uga.edu/CODV2API/api/v1/Themes/cod-ps/Lookup/latlng?latlong=32.098,63.158&wkid=4326&level=1

**Comment by UGA-ITOSHumanitarianGIS** [comment]
This is documented on the help pages. The issue reports no examples are given for requests, the examples are shown on the help and data is provided as per the data on data.humdata.org at the time of the closing of this issue

**Comment by UGA-ITOSHumanitarianGIS** [comment]
These examples are also available on the production api:

https://apps.itos.uga.edu/CODV2API/Help/Api/GET-api-v1-themes-cod-ps-Lookup-latlng-latlong-wkid-level
